import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { NavBar } from "./components/homepage/NavBar";
import { Profile } from "./components/homepage/Profile";
import { ServiceIntro } from "./components/homepage/ServiceIntro";
import { ServiceBody } from "./components/homepage/ServiceBody";
import PortfolioIntro from "./components/homepage/PortfolioIntro";
import { PortfolioBody } from "./components/homepage/PortfolioBody";
import { Dsec } from "./components/homepage/Dsec";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Uche Chris</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white dark:bg-gray-900  ">
        <section className="min-h-screen">

          
          <nav className="p-10  md:px-20 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyed</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="hover:text-opacity-80 cursor-pointer bg-gradient-to-r from-cyan-500  to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="http:///C:/Users/Uche%20Chris/Downloads/Uche%20Chris%20FrontEnd%20Resume.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <Profile/>
         
        </section>
        {/* <section>
          <ServiceIntro/>
          
          <ServiceBody/>
          
        </section>
        <section className="py-10">
          <PortfolioIntro/>
          
          <PortfolioBody/>
          
        </section> */}
      </main>
    </div>
  );
}
