import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Link from "next/link";
import { motion as m } from "framer-motion";
import { Profile } from "./components/homepage/Profile";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <m.div className={`${darkMode ? "dark" : ""}`}
           initial={{y: "100%"}} 
           animate={{y: "0%"}} 
           exit={{opacity:1}}
           transition={{duration:1, ease: "easeOut"}}>
      <Head>
        <title>Uche Chris</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white dark:bg-gray-900  ">
        <section className="min-h-screen">

          
          {/* <nav className="p-10  md:px-20 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developedbyed</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <Link href="/Contact">
                <li>
                  <a
                    className="hover:text-opacity-80 cursor-pointer bg-gradient-to-r from-cyan-500  to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                    href="http:///C:/Users/Uche%20Chris/Downloads/Uche%20Chris%20FrontEnd%20Resume.pdf"
                  >
                    Resume
                  </a>
                </li>
              </Link>
              
            </ul>
          </nav> */}
          <Profile/>
         
        </section>
        {/* <section>
          <ServiceIntro/>
          
          <ServiceBody/>
          
        </section>
        <section className="py-10">
          <PortfolioIntro/>
          
          <PortfolioBody/>
          
        </section> */}
      </main>
    </m.div>
  );
}
